/*
 * keymap.h
 *
 *  Created on: 2020/05/23
 *      Author: nonoho
 */

#pragma once

#include "usb_hid_keys.h"
#include <stdint.h>

// MAP，IN，OUT
const uint8_t keycode_table[1][8][16] = { { // MAP: 0
        { KEY_ESC, KEY_F1, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_F10, KEY_F11, KEY_F12, KEY_SYSRQ, KEY_SCROLLLOCK, KEY_END }, // OUT:00
                { KEY_GRAVE, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0, KEY_MINUS, KEY_EQUAL, KEY_BACKSPACE, KEY_HOME, KEY_PAGEUP }, // OUT:01
                { KEY_TAB, KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_Y, KEY_U, KEY_I, KEY_O, KEY_P, KEY_LEFTBRACE, KEY_RIGHTBRACE, KEY_BACKSLASH, KEY_PAUSE, KEY_PAGEDOWN }, // OUT:02
                { KEY_LEFTCTRL, KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_H, KEY_J, KEY_K, KEY_L, KEY_SEMICOLON, KEY_APOSTROPHE, KEY_ENTER, KEY_RIGHTSHIFT, KEY_DELETE, KEY_UP }, // OUT:03
                { KEY_LEFTSHIFT, KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M, KEY_COMMA, KEY_DOT, KEY_SLASH, KEY_COMPOSE, KEY_RIGHTCTRL, KEY_LEFT, KEY_DOWN, KEY_RIGHT }, // OUT:04
                { KEY_LEFTCTRL, KEY_INSERT, KEY_LEFTMETA, KEY_LEFTALT, KEY_MUHENKAN, KEY_SPACE, KEY_HENKAN, KEY_KATAKANA, KEY_RIGHTALT, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE }, // OUT:05
                { KEY_NUMLOCK, KEY_KPSLASH, KEY_KPASTERISK, KEY_KPMINUS, KEY_KP7, KEY_KP8, KEY_KP9, KEY_KPPLUS, KEY_KP4, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE }, // OUT:06
                { KEY_KP5, KEY_KP6, KEY_KP1, KEY_KP2, KEY_KP3, KEY_KPENTER, KEY_KP0, KEY_KPDOT, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE }, // OUT:07
        } };
